### PR TITLE
Design features

### PR DESCRIPTION
**Pull request by Isabelle36**
I have Done the Header ,font and added some of the glow and a slight of animated background.  BTW (I have maded a issue for customizing the form look please review it nd lemme know)

### CODE REVIEW

**Review by d-coder111 — APPROVED** [review]
This looks great👍😊...Kindly consider starring the repository to show your support🌟👍. Any meaningful contributions are welcomed!

**Comment by d-coder111** [comment]
Hey @Isabelle36, add your name in the contributors.md list.

**Comment by Isabelle36** [comment]
> Hey @Isabelle36, add your name in the contributors.md list.

I will do it by tomorrow

**Comment by d-coder111** [comment]
Anyway I am removing that file...should have maintained that from the very start.

**Comment by Isabelle36** [comment]
i cant able to find a file named contributers.md could u help me out on this

**Comment by d-coder111** [comment]
> i cant able to find a file named contributers.md could u help me out on this

I removed that yesterday.

**Comment by Isabelle36** [comment]
So now how can I add my name to it u said we need to add it in the
contributors

**Pull request merged**
