### PR TITLE
refactor: spells section

### PR DESCRIPTION
**Pull request by iamDyeus**
I didn’t make any major changes due to the current project structure, which limited the use of external libraries or extensions. However, here are the updates I made:

- Improved the interpretation of the spells section in `index.html`.
- Updated the CSS for the spells section to enhance its styling.
- Modified the `spells` constant in the JavaScript file by adding emojis to make it more engaging and fun.

### CODE REVIEW

**Comment by d-coder111** [comment]
Ok, will review it.

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Hey, I think the previous designs looked better but you can add emojis in the spells.

**Comment by iamDyeus** [comment]
> Hey, I think the previous designs looked better but you can add emojis in the spells.

Okay got it, I'll do the requested changes by today.

**Comment by d-coder111** [comment]
Hey create a new fork and do the changes and raise a new pr, that would be easy for me to review the changes, so I am closing this one.

**Pull request closed without merging**
