### PR TITLE
Adding Sound Effects to the Hogwarts Quiz Website

### PR DESCRIPTION
**Pull request by mahenoorsalat**
**Pull request : Add sound effects to enhance the overall user experience.**

- Fixes issue #8

**Changes made :**

- [x] Added a background audio element that plays Hogwarts-themed music continuously across the website, creating an immersive experience for users.

- [x] Incorporated a sound effect that plays when the quiz form is submitted, enhancing user interaction and feedback upon submission.

- [x] Used JavaScript to prevent the default form submission action, allowing the sound effect to play before any further actions are taken, ensuring a smooth user experience.

Looking forward to your response on this pr..

Thank you :)

Ping @d-coder111

### CODE REVIEW

**Comment by d-coder111** [comment]
Hey @mahenoorsalat , can you pls update your repo once and then create a pr.

**Comment by mahenoorsalat** [comment]
as I already updated it :)

**Comment by d-coder111** [comment]
> as I already updated it :)

ok let me just test it once, then i will merge it.

**Comment by d-coder111** [comment]
Hey @mahenoorsalat , can you make changes in the updated files and then create a pr, because after running your files the whole website seems distorted since you made changes in the previous files.

**Comment by d-coder111** [comment]
web_1
web_2
web_3

**Comment by mahenoorsalat** [comment]
okay but this is the current website like this only seen I didn't change the structure I just added sound effects

**Comment by mahenoorsalat** [comment]
And let me do another pr for this after adding the sound effects okay ? :)

**Comment by d-coder111** [comment]
> And let me do another pr for this after adding the sound effects okay ? :)

hey make changes in the new updated files.

**Pull request closed without merging**
