### PR TITLE
Massive Improvements made to the quiz.

### PR DESCRIPTION
**Pull request by DewashishCodes**
List of improvemnets made:

1.Added a banner image on top of the quiz.
2.Added aesthetic elements to the quiz with hover changes in appearance. Change in colors as the page looks more appealing to the eye.
2. Along with the answer the logo of the respective house also is visible.

Hope you like this and merge my pr.

Happy coding ! ! !

### CODE REVIEW

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Hey @DewashishCodes , place the banner picture in the middle or make it cover full space at the top.
Rest everything looks fine👍😊.

**Review by d-coder111 — COMMENTED** [review]
Also do add ur name in the contributors list once you are done with the banner correction.

**Comment by DewashishCodes** [comment]
> Hey @DewashishCodes , place the banner picture in the middle or make it cover full space at the top.
> Rest everything looks fine👍😊.

Hey Hi, If you don't mind can you merge this PR first as multiple commits on the same PR is flagged as spam by Hacktoberfest automatically. A contributor I talked to earlier this morning got banned from Hacktober due to 2 spam flags. Hope you understand and merge the PR. I'll instantly make the changes and execute a PR .

**Comment by d-coder111** [comment]
> > Hey @DewashishCodes , place the banner picture in the middle or make it cover full space at the top.
> > Rest everything looks fine👍😊.
> 
> Hey Hi, If you don't mind can you merge this PR first as multiple commits on the same PR is flagged as spam by Hacktoberfest automatically. A contributor I talked to earlier this morning got banned from Hacktober due to 2 spam flags. Hope you understand and merge the PR. I'll instantly make the changes and execute a PR .

ok no problem👍. But when you do the changes...add ur name in the contributors list in the readme file as per the format.

**Review by d-coder111 — APPROVED** [review]

**Comment by d-coder111** [comment]
Hey @DewashishCodes add your name in the contributors.md list.

**Pull request merged**
