### PR TITLE
Theme changes update

### PR DESCRIPTION
**Pull request by sunny7899**

### CODE REVIEW

**Review by d-coder111 — COMMENTED** [review]
Hey you have added banner twice and even the formatting and design part doesn't quite fit.

**Comment by sunny7899** [comment]
@d-coder111  why you are closing the PR again and again you can add comment i will fix you can merge it. is this ok?

**Comment by sunny7899** [comment]
@d-coder111  let me fix it its due to code conflict

**Comment by d-coder111** [comment]
Also I want a harry potter themed website..incase you want to focus on theme of the website..not any black or white.

**Comment by sunny7899** [comment]
If possible, can you merge this with tag later so we can take enhancement? corrected that image issue. @d-coder111

**Comment by d-coder111** [comment]
Look, I tested your code and the design and formatting was not upto the mark ..you can try and focus on other aspect of the project..because many others are working to make it better.

**Comment by sunny7899** [comment]
you can close the PR

**Pull request closed without merging**
