### PR TITLE
Add_Theme_options

### PR DESCRIPTION
**Pull request by LoayTarek5**
Add features according to this issue https://github.com/d-coder111/The-Wizards-Sorting-Hat/issues/9

### CODE REVIEW

**Comment by LoayTarek5** [comment]
oh ok wait i forget to add somthing

**Comment by d-coder111** [comment]
> oh ok wait i forget to add somthing

ok.

**Comment by LoayTarek5** [comment]
@d-coder111 and please do not forget add to Hacktoberfest

**Comment by d-coder111** [comment]
Hey @LoayTarek5 ,
Kindly consider starring the repo to show ur support✨✌ and feel free to make better design I will merge them.
Maybe a little lighter colors or whatever enhances the overall look of the website, raise a pr if you make a better one, I will merge it. This one I am merging but feel free to give ur input in the project.

**Pull request merged**
