### PR TITLE
Highlight Selected Option to Differentiate from Unselected Ones #53

### PR DESCRIPTION
**Pull request by saarakhan**
image
**Enhanced Styling:**

- Selected options are now highlighted with a gradient green background.
- Added shadows and increased size to make selected options stand out.
- Overall styling improvements for a more visually appealing quiz interface.

### CODE REVIEW

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Hey @saarakhan , I want the selected options to get highlighted in their place only.

**Comment by saarakhan** [comment]
image
okay removed the extra increase!

**Review by d-coder111 — APPROVED** [review]
Looks good👍😊..consider starring the repository to show your support🌟👍. Any meaningful contributions are welcomed!..Happy coding..Happy learning✨

**Comment by saarakhan** [comment]
hey can you add gssoc-ext label

**Pull request merged**
