### PR TITLE
Sounds added in updated file 

### PR DESCRIPTION
**Pull request by mahenoorsalat**
- fixes issue #8

Hy @d-coder111 

This pr is ready to review :)

Looking forward to your response .. Thank you 👍

### CODE REVIEW

**Comment by d-coder111** [comment]
Hey @mahenoorsalat , I want you to know that sorted button sound is playing not the background sound, so could you correct it?That diagon_alley sound would be cool to have.

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Background sound needs to be fixed.

**Comment by mahenoorsalat** [comment]
> Background sound needs to be fixed.

okay :)

**Comment by mahenoorsalat** [comment]
It would be great if the background audio doesn't play automatically, as this could be considered poor UX. Instead, I made the background audio play when the user interacts with the site, such as when they click on "Today's Spell." This provides a more immersive experience without being intrusive, allowing the user to engage with the site at their own pace.

I hope you like this approach!

Thank you!

Ping @d-coder111

**Comment by d-coder111** [comment]
Hey @mahenoorsalat ,pls update your repo and then make changes and create a pr, I will merge them after testing them.

**Comment by mahenoorsalat** [comment]
okay but I already updated it and after only I pushed .. you know that many people are committing so please check those pr on time 

hope you don't mind it :)

Thank you @d-coder111

**Comment by d-coder111** [comment]
web
 Hey @mahenoorsalat , Why have you removed this?

**Comment by d-coder111** [comment]
Anyway, I will correct that and now merging your pr👍..consider starring the repo to show ur support⭐..and you are welcome to contribute as many valid contributions you can make😊✌.

**Review by d-coder111 — APPROVED** [review]

**Comment by mahenoorsalat** [comment]
Maybe it done by mistake  ... 

Okay I'm ready for further contribution and now I'm focusing on animation and all 

thanks:) @d-coder111

**Comment by d-coder111** [comment]
> Maybe it done by mistake ...
> 
> Okay I'm ready for further contribution and now I'm focusing on animation and all
> 
> thanks:) @d-coder111

No worries, I have added it.👍..happy coding..happy learning🚀😊

**Pull request merged**
